// styles/AppStyles.js
import { palette } from '../constants/colors';

export const styles = {
// Container principal avec design moderne
  container: {
    minHeight: '100vh',
    backgroundColor: palette.bgPrimary,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif",
    position: 'relative',
  },

  // Navigation moderne avec glassmorphism
  navigation: {
    display: 'flex',
    backgroundColor: palette.bgGlass,
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: `1px solid ${palette.borders.light}`,
    padding: '12px 20px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: palette.shadows.sm,
  },
  navButton: {
    flex: 1,
    padding: '14px 20px',
    margin: '0 6px',
    borderRadius: '16px',
    background: 'transparent',
    border: `2px solid transparent`,
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: '600',
    color: palette.textSecondary,
    textAlign: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    overflow: 'hidden',
  },
  activeNavButton: {
    background: palette.gradients.primary,
    color: palette.textWhite,
    transform: 'translateY(-2px)',
    boxShadow: palette.shadows.glow,
    border: `2px solid ${palette.accent}`,
  },

  // Sélecteur de langue moderne
  languageSelector: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    zIndex: 200,
  },
  languageButton: {
    background: palette.bgGlass,
    backdropFilter: 'blur(10px)',
    border: `1px solid ${palette.borders.light}`,
    borderRadius: '12px',
    padding: '10px 15px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: palette.textPrimary,
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  languageDropdown: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: '8px',
    background: palette.bgCard,
    borderRadius: '12px',
    boxShadow: palette.shadows.modal,
    border: `1px solid ${palette.borders.light}`,
    overflow: 'hidden',
    minWidth: '200px',
  },
  languageOption: {
    padding: '12px 16px',
    cursor: 'pointer',
    fontSize: '14px',
    color: palette.textPrimary,
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },

  // Header moderne avec gradients
  header: {
    background: palette.gradients.primary,
    padding: '40px 30px',
    textAlign: 'center',
    color: palette.textWhite,
    position: 'relative',
    overflow: 'hidden',
  },
  headerTitle: {
    fontSize: '32px',
    fontWeight: '700',
    margin: '0 0 8px 0',
    letterSpacing: '-0.5px',
  },
  headerSubtitle: {
    fontSize: '16px',
    margin: '0',
    opacity: '0.9',
    fontWeight: '400',
  },

  // Cards modernes avec glassmorphism
  card: {
    backgroundColor: palette.bgCard,
    margin: '20px',
    padding: '30px',
    borderRadius: '20px',
    boxShadow: palette.shadows.card,
    border: `1px solid ${palette.borders.light}`,
    transition: 'all 0.3s ease',
    position: 'relative',
  },
  cardHover: {
    transform: 'translateY(-4px)',
    boxShadow: palette.shadows.float,
  },
  cardTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: palette.textPrimary,
    marginBottom: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },

  // Grille d'aliments modernisée avec catégories
  categoryTabs: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  categoryTab: {
    padding: '10px 16px',
    borderRadius: '12px',
    border: `2px solid ${palette.borders.light}`,
    background: palette.bgSecondary,
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: palette.textSecondary,
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  activeCategoryTab: {
    background: palette.gradients.primary,
    color: palette.textWhite,
    border: `2px solid ${palette.primary}`,
    transform: 'scale(1.05)',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(100px, 1fr))',
    gap: '16px',
    marginTop: '20px',
  },
  gridItem: {
    aspectRatio: '1',
    backgroundColor: palette.bgCard,
    borderRadius: '16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    border: `2px solid ${palette.borders.light}`,
    padding: '12px',
    boxShadow: palette.shadows.sm,
    position: 'relative',
    overflow: 'hidden',
  },
  gridItemHover: {
    transform: 'scale(1.08) translateY(-4px)',
    boxShadow: palette.shadows.float,
    border: `2px solid ${palette.primary}`,
  },
  gridIcon: {
    fontSize: '32px',
    marginBottom: '8px',
    filter: 'drop-shadow(0 2px 4px rgba(0,0,0,0.1))',
  },
  gridText: {
    fontSize: '12px',
    color: palette.textPrimary,
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: '1.2',
  },

  // Inputs modernes avec design épuré
  inputGroup: {
    marginBottom: '20px',
  },
  inputLabel: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '600',
    color: palette.textPrimary,
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    padding: '16px 20px',
    marginBottom: '16px',
    border: `2px solid ${palette.borders.light}`,
    borderRadius: '12px',
    fontSize: '16px',
    boxSizing: 'border-box',
    transition: 'all 0.2s ease',
    backgroundColor: palette.bgCard,
    outline: 'none',
    fontFamily: 'inherit',
  },
  inputFocus: {
    borderColor: palette.primary,
    boxShadow: `0 0 0 3px ${palette.states.focus}`,
  },
  inputRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 2fr',
    gap: '16px',
  },

  // Boutons modernes avec animations
  // Boutons modernes avec animations
  button: {
    padding: '16px 24px',
    borderRadius: '12px',
    border: 'none',
    color: palette.textWhite,
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    margin: '8px',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    boxSizing: 'border-box',
    position: 'relative',
    overflow: 'hidden',
    fontFamily: 'inherit',
    outline: 'none',
  },
  buttonHover: {
    transform: 'translateY(-2px)',
    boxShadow: palette.shadows.float,
  },
  successButton: {
    background: palette.gradients.success,
    boxShadow: palette.shadows.button,
  },
  warningButton: {
    background: palette.gradients.warning,
    boxShadow: palette.shadows.button,
  },
  infoButton: {
    background: palette.gradients.info,
    boxShadow: palette.shadows.button,
  },
  dangerButton: {
    background: palette.gradients.danger,
    boxShadow: palette.shadows.button,
  },
  primaryButton: {
    background: palette.gradients.primary,
    boxShadow: palette.shadows.button,
  },
  buttonRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginTop: '20px',
  },
  buttonIcon: {
    marginRight: '8px',
    fontSize: '16px',
  },

  // Inventaire moderne avec design épuré
  inventoryGrid: {
    display: 'grid',
    gap: '16px',
    marginTop: '20px',
  },
  inventoryItem: {
    display: 'flex',
    backgroundColor: palette.bgCard,
    padding: '20px',
    borderRadius: '16px',
    alignItems: 'center',
    boxShadow: palette.shadows.sm,
    border: `1px solid ${palette.borders.light}`,
    transition: 'all 0.2s ease',
    position: 'relative',
  },
  inventoryItemHover: {
    transform: 'translateY(-2px)',
    boxShadow: palette.shadows.card,
  },
  inventoryInfo: {
    flex: 1,
    marginRight: '16px',
  },
  inventoryName: {
    fontSize: '18px',
    fontWeight: '700',
    color: palette.textPrimary,
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  inventoryIcon: {
    fontSize: '24px',
    filter: 'drop-shadow(0 2px 4px rgba(0,0,0,0.1))',
  },
  quantityControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
    background: palette.bgSecondary,
    borderRadius: '12px',
    padding: '8px 12px',
  },
  quantityButton: {
    backgroundColor: palette.primary,
    color: palette.textWhite,
    border: 'none',
    borderRadius: '8px',
    width: '36px',
    height: '36px',
    cursor: 'pointer',
    fontSize: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
    fontWeight: '600',
  },
  quantityButtonHover: {
    transform: 'scale(1.1)',
    boxShadow: palette.shadows.button,
  },
  inventoryQuantity: {
    fontSize: '16px',
    color: palette.textPrimary,
    fontWeight: '600',
    minWidth: '120px',
    textAlign: 'center',
  },
  inventoryExpiry: {
    fontSize: '13px',
    color: palette.textSecondary,
    fontWeight: '500',
    padding: '4px 8px',
    borderRadius: '8px',
    background: palette.bgSecondary,
  },
  deleteButton: {
    backgroundColor: palette.danger,
    color: palette.textWhite,
    border: 'none',
    borderRadius: '12px',
    width: '48px',
    height: '48px',
    cursor: 'pointer',
    fontSize: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
    boxShadow: palette.shadows.sm,
  },
  deleteButtonHover: {
    transform: 'scale(1.1)',
    boxShadow: palette.shadows.button,
  },

  // État vide moderne
  emptyState: {
    textAlign: 'center',
    padding: '60px 30px',
    color: palette.textSecondary,
  },
  emptyIcon: {
    fontSize: '64px',
    marginBottom: '20px',
    opacity: '0.6',
  },
  emptyTitle: {
    fontSize: '20px',
    fontWeight: '600',
    color: palette.textPrimary,
    marginBottom: '8px',
  },
  emptyText: {
    fontSize: '16px',
    lineHeight: '1.5',
    color: palette.textSecondary,
  },

  // Checkboxes modernes
  checkboxContainer: {
    display: 'grid',
    gap: '12px',
    marginTop: '16px',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px',
    cursor: 'pointer',
    borderRadius: '12px',
    transition: 'all 0.2s ease',
    border: `2px solid transparent`,
  },
  checkboxRowHover: {
    backgroundColor: palette.bgSecondary,
    border: `2px solid ${palette.borders.medium}`,
  },
  checkbox: {
    width: '24px',
    height: '24px',
    borderRadius: '6px',
    border: `2px solid ${palette.borders.medium}`,
    marginRight: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
    position: 'relative',
  },
  checkboxActive: {
    background: palette.gradients.primary,
    border: `2px solid ${palette.primary}`,
    boxShadow: `0 0 0 3px ${palette.states.focus}`,
  },
  checkmark: {
    color: palette.textWhite,
    fontSize: '14px',
    fontWeight: '700',
  },
  checkboxContent: {
    flex: 1,
  },
  checkboxTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: palette.textPrimary,
    marginBottom: '4px',
  },
  checkboxDescription: {
    fontSize: '14px',
    color: palette.textSecondary,
    lineHeight: '1.4',
  },

  // Cartes d'information modernes
  infoCard: {
    background: palette.gradients.glass,
    backdropFilter: 'blur(10px)',
    border: `1px solid ${palette.borders.light}`,
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '20px',
  },
  infoCardIcon: {
    fontSize: '32px',
    marginBottom: '12px',
  },
  infoCardTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: palette.textPrimary,
    marginBottom: '8px',
  },
  infoCardDescription: {
    fontSize: '15px',
    color: palette.textSecondary,
    lineHeight: '1.5',
    marginBottom: '16px',
  },

  // STYLES POUR RECIPE DISPLAY MANAGER MODERNISÉS
  recipeModalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(26, 26, 46, 0.6)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  recipeModalContent: {
    backgroundColor: palette.bgCard,
    borderRadius: '24px',
    width: '100%',
    maxWidth: '1000px',
    maxHeight: '90vh',
    overflow: 'hidden',
    boxShadow: palette.shadows.modal,
    border: `1px solid ${palette.borders.light}`,
  },
  recipeHeader: {
    background: palette.gradients.primary,
    padding: '32px',
    textAlign: 'center',
    color: palette.textWhite,
    position: 'relative',
  },
  recipeHeaderTitle: {
    fontSize: '28px',
    fontWeight: '700',
    margin: '0 0 8px 0',
    letterSpacing: '-0.5px',
  },
  recipeHeaderSubtitle: {
    fontSize: '16px',
    margin: '0',
    opacity: '0.9',
    fontWeight: '400',
  },
  recipeContent: {
    padding: '32px',
    maxHeight: '60vh',
    overflowY: 'auto',
  },

  // Page d'accueil des recettes modernisée
  recipeOverviewCard: {
    background: palette.gradients.glass,
    backdropFilter: 'blur(10px)',
    border: `1px solid ${palette.borders.light}`,
    borderRadius: '20px',
    padding: '32px',
    textAlign: 'center',
    marginBottom: '24px',
  },
  recipeStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '20px',
    margin: '24px 0',
  },
  recipeStatCard: {
    background: palette.bgCard,
    borderRadius: '16px',
    padding: '20px',
    textAlign: 'center',
    border: `1px solid ${palette.borders.light}`,
    transition: 'all 0.2s ease',
  },
  recipeStatIcon: {
    fontSize: '32px',
    marginBottom: '8px',
  },
  recipeStatNumber: {
    fontSize: '24px',
    fontWeight: '700',
    marginBottom: '4px',
  },
  recipeStatLabel: {
    fontSize: '14px',
    color: palette.textSecondary,
    fontWeight: '500',
  },
  recipePageGrid: {
    display: 'grid',
    gap: '12px',
    marginTop: '24px',
  },
  recipePageButton: {
    padding: '16px 20px',
    backgroundColor: palette.bgCard,
    border: `2px solid ${palette.borders.light}`,
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: palette.textPrimary,
    transition: 'all 0.2s ease',
    textAlign: 'left',
  },
  recipePageButtonHover: {
    backgroundColor: palette.primary,
    color: palette.textWhite,
    transform: 'translateY(-2px)',
    boxShadow: palette.shadows.button,
  },

  // Cards de recettes modernisées
  recipeCard: {
    backgroundColor: palette.bgCard,
    borderRadius: '20px',
    padding: '24px',
    marginBottom: '20px',
    boxShadow: palette.shadows.card,
    border: `1px solid ${palette.borders.light}`,
    transition: 'all 0.3s ease',
  },
  recipeCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
  },
  recipeTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: palette.textPrimary,
    flex: 1,
    marginRight: '16px',
    margin: 0,
    lineHeight: '1.3',
  },
  recipeScore: {
    fontSize: '12px',
    fontWeight: '600',
    padding: '6px 12px',
    borderRadius: '20px',
    background: palette.gradients.success,
    color: palette.textWhite,
    whiteSpace: 'nowrap',
  },
  recipeInfo: {
    marginBottom: '16px',
  },
  recipeInfoText: {
    fontSize: '14px',
    color: palette.textSecondary,
    marginBottom: '6px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  recipeIngredientsList: {
    fontSize: '13px',
    color: palette.textSecondary,
    fontStyle: 'italic',
    background: palette.bgSecondary,
    padding: '12px 16px',
    borderRadius: '12px',
    marginTop: '12px',
    lineHeight: '1.4',
  },

  // Boutons d'action pour recettes
  recipeActionButtons: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '12px',
    marginTop: '20px',
  },
  recipeDetailButton: {
    padding: '12px 20px',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    background: palette.gradients.primary,
    color: palette.textWhite,
  },
  recipeUrlButton: {
    padding: '12px 20px',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    background: palette.gradients.info,
    color: palette.textWhite,
  },

  // Navigation des recettes modernisée
  recipeNavigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '24px 32px',
    background: palette.bgSecondary,
    borderTop: `1px solid ${palette.borders.light}`,
  },
  recipeNavButton: {
    padding: '12px 20px',
    background: palette.gradients.primary,
    color: palette.textWhite,
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    margin: '0 8px',
    transition: 'all 0.2s ease',
  },
  recipeActiveNavButton: {
    background: palette.gradients.success,
    transform: 'scale(1.05)',
  },
  recipePageInfo: {
    fontSize: '15px',
    color: palette.textPrimary,
    fontWeight: '600',
  },

  // Modal de détails modernisé
  recipeDetailsModal: {
    backgroundColor: palette.bgCard,
    borderRadius: '24px',
    width: '95%',
    maxWidth: '800px',
    maxHeight: '85vh',
    overflow: 'hidden',
    boxShadow: palette.shadows.modal,
  },
  recipeDetailsContent: {
    padding: '32px',
    maxHeight: '65vh',
    overflowY: 'auto',
  },
  recipeDetailsTitle: {
    fontSize: '24px',
    fontWeight: '700',
    color: palette.textPrimary,
    textAlign: 'center',
    marginBottom: '20px',
    lineHeight: '1.3',
  },
  recipeDetailsInfo: {
    display: 'flex',
    justifyContent: 'center',
    gap: '32px',
    marginBottom: '28px',
    flexWrap: 'wrap',
  },
  recipeDetailsInfoItem: {
    fontSize: '15px',
    color: palette.textSecondary,
    textAlign: 'center',
    padding: '12px 16px',
    background: palette.bgSecondary,
    borderRadius: '12px',
    fontWeight: '500',
  },
  recipeSectionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: palette.textPrimary,
    marginBottom: '16px',
    marginTop: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  recipeIngredientItem: {
    fontSize: '14px',
    padding: '8px 0',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: `1px solid ${palette.borders.light}`,
  },
  recipeInstructionsText: {
    fontSize: '14px',
    color: palette.textSecondary,
    lineHeight: '1.6',
    whiteSpace: 'pre-line',
    background: palette.bgSecondary,
    padding: '20px',
    borderRadius: '12px',
  },

  // Close button modernisé
  recipeCloseButton: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    backgroundColor: palette.danger,
    color: palette.textWhite,
    border: 'none',
    borderRadius: '12px',
    width: '44px',
    height: '44px',
    cursor: 'pointer',
    fontSize: '20px',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  closeButtonHover: {
    transform: 'scale(1.1)',
    boxShadow: palette.shadows.button,
  },

  // États de chargement
  loading: {
    opacity: 0.6,
    pointerEvents: 'none',
    position: 'relative',
  },
  loadingSpinner: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '32px',
    height: '32px',
    border: `3px solid ${palette.borders.light}`,
    borderTop: `3px solid ${palette.primary}`,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },

  // Responsive design modernisé
  '@media (max-width: 768px)': {
    container: {
      padding: '0',
    },
    navigation: {
      padding: '8px 12px',
      flexDirection: 'row',
    },
    navButton: {
      padding: '10px 8px',
      fontSize: '12px',
      margin: '0 2px',
    },
    card: {
      margin: '12px',
      padding: '20px',
    },
    header: {
      padding: '24px 20px',
    },
    headerTitle: {
      fontSize: '24px',
    },
    grid: {
      gridTemplateColumns: 'repeat(auto-fill, minmax(80px, 1fr))',
      gap: '12px',
    },
    buttonRow: {
      gridTemplateColumns: '1fr',
      gap: '12px',
    },
    recipeModalContent: {
      width: '95%',
      margin: '10px',
      borderRadius: '16px',
    },
    recipeContent: {
      padding: '20px',
    },
    recipeNavigation: {
      padding: '16px',
      flexDirection: 'column',
      gap: '12px',
    },
    inventoryItem: {
      flexDirection: 'column',
      gap: '12px',
      textAlign: 'center',
    },
    quantityControls: {
      justifyContent: 'center',
    }
  }
};
